/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import controller.PlantController2;
public class DeleteupdatedTasks extends javax.swing.JFrame {

    /**
     * Creates new form deleteupdatedtasks
     */
    public DeleteupdatedTasks() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dieseaseid1 = new javax.swing.JTextField();
        Deletedata = new javax.swing.JButton();
        previous = new javax.swing.JButton();
        plantidtext = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Delete3 = new javax.swing.JButton();
        Delete4 = new javax.swing.JButton();

        dieseaseid1.setBackground(new java.awt.Color(211, 216, 210));
        dieseaseid1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dieseaseid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dieseaseid1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Deletedata.setBorderPainted(false);
        Deletedata.setContentAreaFilled(false);
        Deletedata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletedataActionPerformed(evt);
            }
        });
        getContentPane().add(Deletedata, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 330, 140, 50));

        previous.setBorderPainted(false);
        previous.setContentAreaFilled(false);
        previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousActionPerformed(evt);
            }
        });
        getContentPane().add(previous, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, 90, 50));

        plantidtext.setBackground(new java.awt.Color(211, 216, 210));
        plantidtext.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        plantidtext.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                plantidtextComponentAdded(evt);
            }
        });
        plantidtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plantidtextActionPerformed(evt);
            }
        });
        getContentPane().add(plantidtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 470, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/deleteupdatedtasks copy.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 800));

        Delete3.setBorderPainted(false);
        Delete3.setContentAreaFilled(false);
        Delete3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete3ActionPerformed(evt);
            }
        });
        getContentPane().add(Delete3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 150, 60));

        Delete4.setBorderPainted(false);
        Delete4.setContentAreaFilled(false);
        Delete4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete4ActionPerformed(evt);
            }
        });
        getContentPane().add(Delete4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 150, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dieseaseid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dieseaseid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dieseaseid1ActionPerformed

    private void plantidtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plantidtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plantidtextActionPerformed

    private void plantidtextComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_plantidtextComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_plantidtextComponentAdded

    private void DeletedataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletedataActionPerformed
        // TODO add your handling code here:
        try {
        // Get the plant ID from the text field
        int plantId = Integer.parseInt(plantidtext.getText().trim());
        
        // Show confirmation dialog
        int choice = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to delete Plant ID: " + plantId + "?",
            "Confirm Deletion",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
        
        // Check user's choice
        if (choice == JOptionPane.YES_OPTION) {
            // User clicked Yes, proceed with deletion
            PlantController2 controller = new PlantController2();
            boolean success = controller.deletePlant(plantId);
            
            if (success) {
                JOptionPane.showMessageDialog(this, 
                    "Plant with ID " + plantId + " successfully deleted.",
                    "Success", JOptionPane.INFORMATION_MESSAGE);
                plantidtext.setText(""); // Clear the text field
            } else {
                JOptionPane.showMessageDialog(this,
                    "No plant found with ID " + plantId,
                    "Not Found", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            // User clicked No, do nothing
            JOptionPane.showMessageDialog(this,
                "Deletion cancelled by user.",
                "Cancelled", JOptionPane.INFORMATION_MESSAGE);
        }
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
            "Please enter a valid Plant ID number",
            "Input Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_DeletedataActionPerformed

    private void previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousActionPerformed
        // TODO add your handling code here:          
        UpdateTask view = new UpdateTask  ();
        view.setVisible(true);
        this.dispose();  
    }//GEN-LAST:event_previousActionPerformed

    private void Delete3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Delete3ActionPerformed

    private void Delete4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Delete4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteupdatedTasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteupdatedTasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteupdatedTasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteupdatedTasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteupdatedTasks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete3;
    private javax.swing.JButton Delete4;
    private javax.swing.JButton Deletedata;
    private javax.swing.JTextField dieseaseid1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField plantidtext;
    private javax.swing.JButton previous;
    // End of variables declaration//GEN-END:variables
}
