/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Administrator
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import controller.DutController;
import javax.swing.JOptionPane;
public class DeleteupdatedTreatments extends javax.swing.JFrame {
 private DutController controller;
    /**
     * Creates new form deleteupdatedtreatments
     */
    public DeleteupdatedTreatments() {
        initComponents();
        controller = new DutController();
        setupDeleteButton();
    }
    private void setupDeleteButton() {
        Delete.addActionListener(evt -> {
            try {
                String diseaseIdText = diseaseid.getText().trim();
                if (diseaseIdText.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Please enter a Disease ID");
                    return;
                }
                
                int diseaseId = Integer.parseInt(diseaseIdText);
                
                int confirm = JOptionPane.showConfirmDialog(
                    this,
                    "Are you sure you want to delete this disease and its treatment?",
                    "Confirm Deletion",
                    JOptionPane.YES_NO_OPTION
                );
                
                if (confirm == JOptionPane.YES_OPTION) {
                    if (controller.deleteDisease(diseaseId)) {
                        JOptionPane.showMessageDialog(this, "Disease deleted successfully");
                        diseaseid.setText("");
                        
                    } else {
                        JOptionPane.showMessageDialog(this, "Failed to delete disease. Please try again.");
                    }
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Please enter a valid Disease ID");
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        diseaseid = new javax.swing.JTextField();
        Delete = new javax.swing.JButton();
        prev = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        diseaseid.setBackground(new java.awt.Color(211, 216, 210));
        diseaseid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        diseaseid.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                diseaseidComponentAdded(evt);
            }
        });
        diseaseid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diseaseidActionPerformed(evt);
            }
        });
        getContentPane().add(diseaseid, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 470, 50));

        Delete.setBorderPainted(false);
        Delete.setContentAreaFilled(false);
        getContentPane().add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 330, 150, 50));

        prev.setBorderPainted(false);
        prev.setContentAreaFilled(false);
        prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevActionPerformed(evt);
            }
        });
        getContentPane().add(prev, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, 90, 50));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/deleteupdatedtreatments.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void diseaseidComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_diseaseidComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_diseaseidComponentAdded

    private void diseaseidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diseaseidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diseaseidActionPerformed

    private void prevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevActionPerformed
        // TODO add your handling code here:
        EnterTreatment view = new EnterTreatment  ();
        view.setVisible(true);
        this.dispose();   
    }//GEN-LAST:event_prevActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteupdatedTreatments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteupdatedTreatments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteupdatedTreatments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteupdatedTreatments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteupdatedTreatments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JLabel background;
    private javax.swing.JTextField diseaseid;
    private javax.swing.JButton prev;
    // End of variables declaration//GEN-END:variables
}
