/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.GreenhouseController;
import javax.swing.JOptionPane;
import model.EnterharvestModel;

/**
 *
 * @author Administrator
 */
public class EnterHarvest extends javax.swing.JFrame {

    /**
     * Creates new form enterharvest
     */
    public EnterHarvest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        greenhouseid = new javax.swing.JTextField();
        searchtreatments1 = new javax.swing.JButton();
        descriptionhar = new javax.swing.JTextField();
        enterhar = new javax.swing.JButton();
        stock = new javax.swing.JTextField();
        seetasks = new javax.swing.JButton();
        updateharvest = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        greenhouseid.setBackground(new java.awt.Color(211, 216, 210));
        greenhouseid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        greenhouseid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenhouseidActionPerformed(evt);
            }
        });
        getContentPane().add(greenhouseid, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 470, 50));

        searchtreatments1.setBorderPainted(false);
        searchtreatments1.setContentAreaFilled(false);
        searchtreatments1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchtreatments1ActionPerformed(evt);
            }
        });
        getContentPane().add(searchtreatments1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 190, 70));

        descriptionhar.setBackground(new java.awt.Color(211, 216, 210));
        descriptionhar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        descriptionhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionharActionPerformed(evt);
            }
        });
        getContentPane().add(descriptionhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 470, 50));

        enterhar.setBorderPainted(false);
        enterhar.setContentAreaFilled(false);
        enterhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterharActionPerformed(evt);
            }
        });
        getContentPane().add(enterhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 420, 130, 50));

        stock.setBackground(new java.awt.Color(211, 216, 210));
        stock.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockActionPerformed(evt);
            }
        });
        getContentPane().add(stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 470, 50));

        seetasks.setBorderPainted(false);
        seetasks.setContentAreaFilled(false);
        seetasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seetasksActionPerformed(evt);
            }
        });
        getContentPane().add(seetasks, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 180, 60));

        updateharvest.setBorderPainted(false);
        updateharvest.setContentAreaFilled(false);
        updateharvest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateharvestActionPerformed(evt);
            }
        });
        getContentPane().add(updateharvest, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 190, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/enterharvest .png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterharActionPerformed
        // TODO add your handling code here:
        String gid1 = greenhouseid.getText();
        int greenhouse_ID= Integer.parseInt(gid1);
        String Description= descriptionhar.getText();
        String stock1 = stock.getText();
        
        
        EnterharvestModel inventory = new EnterharvestModel (greenhouse_ID,Description,stock1);
        
        
        boolean response = GreenhouseController.enterharvest(inventory);
        if(response == true){
            JOptionPane.showMessageDialog(EnterHarvest.this,"harvest record has been saved suceessfully!",
                    "New Record",
                    JOptionPane.INFORMATION_MESSAGE);   
            
            greenhouseid.setText("");
            descriptionhar.setText("");
            stock.setText("");
        }
        else{
            JOptionPane.showMessageDialog(EnterHarvest.this,"The harvest record could not be added!","Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_enterharActionPerformed

    private void seetasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seetasksActionPerformed
          SeeTask view = new SeeTask  ();
        view.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_seetasksActionPerformed

    private void updateharvestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateharvestActionPerformed
          EnterHarvest view = new EnterHarvest ();
        view.setVisible(true);
        this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_updateharvestActionPerformed

    private void greenhouseidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenhouseidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_greenhouseidActionPerformed

    private void descriptionharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionharActionPerformed

    private void stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockActionPerformed

    private void searchtreatments1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchtreatments1ActionPerformed
          SearchTreatment view = new SearchTreatment  ();
        view.setVisible(true);
        this.dispose();           // TODO add your handling code here:
    }//GEN-LAST:event_searchtreatments1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnterHarvest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnterHarvest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnterHarvest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnterHarvest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnterHarvest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField descriptionhar;
    private javax.swing.JButton enterhar;
    private javax.swing.JTextField greenhouseid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton searchtreatments1;
    private javax.swing.JButton seetasks;
    private javax.swing.JTextField stock;
    private javax.swing.JButton updateharvest;
    // End of variables declaration//GEN-END:variables
}
