/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
import javax.swing.*;
import java.awt.event.*;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import model.GreenhouseModelA;
import controller.GreenhouseController;
import javax.swing.JOptionPane;
public class EnterTreatment extends javax.swing.JFrame {

    /**
     * Creates new form entertreatment
     */
    public EnterTreatment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dieseaseid1 = new javax.swing.JTextField();
        Delete = new javax.swing.JButton();
        diseasesymptom1 = new javax.swing.JTextField();
        viewharvest = new javax.swing.JButton();
        diseasetreatment = new javax.swing.JTextField();
        diseasename1 = new javax.swing.JTextField();
        enter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        updatetreatment = new javax.swing.JButton();
        updatetasks1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dieseaseid1.setBackground(new java.awt.Color(211, 216, 210));
        dieseaseid1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dieseaseid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dieseaseid1ActionPerformed(evt);
            }
        });
        getContentPane().add(dieseaseid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, 460, 50));

        Delete.setBorderPainted(false);
        Delete.setContentAreaFilled(false);
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 500, 180, 70));

        diseasesymptom1.setBackground(new java.awt.Color(211, 216, 210));
        diseasesymptom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diseasesymptom1ActionPerformed(evt);
            }
        });
        getContentPane().add(diseasesymptom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, 460, 50));

        viewharvest.setBorderPainted(false);
        viewharvest.setContentAreaFilled(false);
        viewharvest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewharvestActionPerformed(evt);
            }
        });
        getContentPane().add(viewharvest, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 373, 190, 60));

        diseasetreatment.setBackground(new java.awt.Color(211, 216, 210));
        diseasetreatment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diseasetreatmentActionPerformed(evt);
            }
        });
        getContentPane().add(diseasetreatment, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 420, 460, 50));

        diseasename1.setBackground(new java.awt.Color(211, 216, 210));
        diseasename1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diseasename1ActionPerformed(evt);
            }
        });
        getContentPane().add(diseasename1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, 460, 50));

        enter.setBorderPainted(false);
        enter.setContentAreaFilled(false);
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });
        getContentPane().add(enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 500, 180, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/entertreatments copy.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        updatetreatment.setBorderPainted(false);
        updatetreatment.setContentAreaFilled(false);
        updatetreatment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatetreatmentActionPerformed(evt);
            }
        });
        getContentPane().add(updatetreatment, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 180, 60));

        updatetasks1.setBorderPainted(false);
        updatetasks1.setContentAreaFilled(false);
        updatetasks1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatetasks1ActionPerformed(evt);
            }
        });
        getContentPane().add(updatetasks1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 223, 190, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
            // TODO add your handling code here:
            String diseaseid = dieseaseid1.getText();
        int Employeeid = Integer.parseInt(diseaseid);
        
        String diseasename = diseasename1.getText();
        String diseasesymtoms = diseasesymptom1.getText();
        String diseasetreatments = diseasetreatment.getText();
        
        GreenhouseModelA disease = new GreenhouseModelA (Employeeid,diseasename,diseasesymtoms,diseasetreatments);
        
        
        boolean response = GreenhouseController.insert(disease);
        if(response == true){
            JOptionPane.showMessageDialog(EnterTreatment.this,"The record has been saved suceessfully!",
                    "New Record",
                    JOptionPane.INFORMATION_MESSAGE);   
                diseasename1.setText(""); // Clears the text field
                diseasesymptom1.setText("");
                diseasetreatment.setText("");
            dieseaseid1.setText("");

            
        }
        else{
            JOptionPane.showMessageDialog(EnterTreatment.this,"The record could not be added!","Error",
                    JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_enterActionPerformed

    private void viewharvestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewharvestActionPerformed
        ViewHarvest view = new ViewHarvest ();
        view.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_viewharvestActionPerformed

    private void updatetasks1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatetasks1ActionPerformed
        UpdateTask view = new UpdateTask ();
        view.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_updatetasks1ActionPerformed

    private void diseasetreatmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diseasetreatmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diseasetreatmentActionPerformed

    private void dieseaseid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dieseaseid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dieseaseid1ActionPerformed

    private void diseasename1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diseasename1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diseasename1ActionPerformed

    private void diseasesymptom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diseasesymptom1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diseasesymptom1ActionPerformed

    private void updatetreatmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatetreatmentActionPerformed
        EnterTreatment view = new EnterTreatment ();
        view.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_updatetreatmentActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        DeleteupdatedTreatments view = new DeleteupdatedTreatments ();
        view.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_DeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnterTreatment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnterTreatment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnterTreatment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnterTreatment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnterTreatment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JTextField dieseaseid1;
    private javax.swing.JTextField diseasename1;
    private javax.swing.JTextField diseasesymptom1;
    private javax.swing.JTextField diseasetreatment;
    private javax.swing.JButton enter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton updatetasks1;
    private javax.swing.JButton updatetreatment;
    private javax.swing.JButton viewharvest;
    // End of variables declaration//GEN-END:variables
}
