/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Administrator
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
public class Homepage extends javax.swing.JFrame {

    /**
     * Creates new form homepage
     */
    public Homepage() {
        initComponents();
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminbuttton = new javax.swing.JButton();
        workerbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        adminbuttton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminbuttton.setForeground(java.awt.Color.white);
        adminbuttton.setBorderPainted(false);
        adminbuttton.setContentAreaFilled(false);
        adminbuttton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminbutttonActionPerformed(evt);
            }
        });
        getContentPane().add(adminbuttton, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 400, 250, 50));

        workerbutton.setBorderPainted(false);
        workerbutton.setContentAreaFilled(false);
        workerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workerbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(workerbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 520, 250, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homepage.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -20, 1280, 760));

        adminbuttton1.setForeground(java.awt.Color.white);
        adminbuttton1.setBorderPainted(false);
        adminbuttton1.setContentAreaFilled(false);
        adminbuttton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminbuttton1ActionPerformed(evt);
            }
        });
        getContentPane().add(adminbuttton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 420, 250, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminbutttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminbutttonActionPerformed
        AdminLogin view = new AdminLogin();
        view.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_adminbutttonActionPerformed

    private void adminbuttton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminbuttton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminbuttton1ActionPerformed

    private void workerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workerbuttonActionPerformed
        WorkerLogin view = new WorkerLogin();
        view.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_workerbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminbuttton;
    private javax.swing.JButton adminbuttton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton workerbutton;
    // End of variables declaration//GEN-END:variables
}
