/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Administrator
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import controller.DiseaseController;
import model.DiseaseModel;
import java.util.List;
import javax.swing.table.DefaultTableModel;
public class SearchTreatment extends javax.swing.JFrame {
     private DiseaseController controller;  // Declare controller

    public SearchTreatment() {
        initComponents();
        controller = new DiseaseController();  // Initialize controller
    }
    /**
     * Creates new form searchtreatment
     */
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        searchtreatmenttable = new javax.swing.JTable();
        updateharvest = new javax.swing.JButton();
        enterdisease_id = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        moredetails = new javax.swing.JButton();
        searchtreatments = new javax.swing.JButton();
        seetasks = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchtreatmenttable.setBackground(new java.awt.Color(211, 216, 210));
        searchtreatmenttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, "", null},
                {null, null, null, null}
            },
            new String [] {
                "Disease_ID", "Name", "Symptoms", "Treatments"
            }
        ));
        searchtreatmenttable.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        searchtreatmenttable.setEditingRow(5);
        searchtreatmenttable.setGridColor(new java.awt.Color(211, 216, 210));
        searchtreatmenttable.setRowSelectionAllowed(false);
        searchtreatmenttable.setSelectionBackground(new java.awt.Color(211, 216, 210));
        jScrollPane1.setViewportView(searchtreatmenttable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 890, 220));

        updateharvest.setBorderPainted(false);
        updateharvest.setContentAreaFilled(false);
        updateharvest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateharvestActionPerformed(evt);
            }
        });
        getContentPane().add(updateharvest, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 190, 60));

        enterdisease_id.setBackground(new java.awt.Color(211, 216, 210));
        enterdisease_id.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        enterdisease_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterdisease_idActionPerformed(evt);
            }
        });
        getContentPane().add(enterdisease_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 130, 470, 50));

        search.setText("/");
        search.setBorderPainted(false);
        search.setContentAreaFilled(false);
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 270, 150, 40));

        moredetails.setBorderPainted(false);
        moredetails.setContentAreaFilled(false);
        moredetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moredetailsActionPerformed(evt);
            }
        });
        getContentPane().add(moredetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 270, 160, 40));

        searchtreatments.setBorderPainted(false);
        searchtreatments.setContentAreaFilled(false);
        searchtreatments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchtreatmentsActionPerformed(evt);
            }
        });
        getContentPane().add(searchtreatments, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 190, 70));

        seetasks.setBorderPainted(false);
        seetasks.setContentAreaFilled(false);
        seetasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seetasksActionPerformed(evt);
            }
        });
        getContentPane().add(seetasks, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 190, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/searchtreatments copy.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
           try {
        int diseaseId = Integer.parseInt(enterdisease_id.getText().trim());
        DiseaseModel disease = controller.searchDiseaseById(diseaseId);
        DefaultTableModel model = (DefaultTableModel) searchtreatmenttable.getModel();
        controller.updateTableWithDisease(model, disease);
         enterdisease_id.setText(""); // Clear the text field
    } catch (NumberFormatException e) {
        // Handle invalid input
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Please enter a valid Disease ID number",
            "Invalid Input",
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_searchActionPerformed

    private void seetasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seetasksActionPerformed
          SeeTask view = new SeeTask  ();
        view.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_seetasksActionPerformed

    private void searchtreatmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchtreatmentsActionPerformed
     // TODO add your handling code here:
         initComponents();
    controller = new DiseaseController();
    
    // Set up the table model properly
    searchtreatmenttable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {},
        new String [] {
            "Disease_ID", "Name", "Symptoms", "Treatments"
        }
    ));

    }//GEN-LAST:event_searchtreatmentsActionPerformed

    private void updateharvestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateharvestActionPerformed
          EnterHarvest view = new EnterHarvest ();
        view.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_updateharvestActionPerformed

    private void enterdisease_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterdisease_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterdisease_idActionPerformed

    private void moredetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moredetailsActionPerformed
        // TODO add your handling code here:
                  ShowDetails view = new ShowDetails ();
        view.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_moredetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchTreatment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchTreatment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchTreatment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchTreatment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchTreatment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField enterdisease_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton moredetails;
    private javax.swing.JButton search;
    private javax.swing.JButton searchtreatments;
    private javax.swing.JTable searchtreatmenttable;
    private javax.swing.JButton seetasks;
    private javax.swing.JButton updateharvest;
    // End of variables declaration//GEN-END:variables
}
