/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Administrator
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import controller.PlantController;
import model.PlantModel;
public class SeeTask extends javax.swing.JFrame {

    /**
     * Creates new form seetask
     */
    public SeeTask() {
        initComponents();
    PlantController controller = new PlantController(this);
    controller.displayAllPlants();
    }
    public javax.swing.JTable getJTable1() {
    return jTable1;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchtreatments = new javax.swing.JButton();
        seetasks = new javax.swing.JButton();
        toolmonitor = new javax.swing.JButton();
        seeall = new javax.swing.JButton();
        updateharvest = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchtreatments.setBorderPainted(false);
        searchtreatments.setContentAreaFilled(false);
        searchtreatments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchtreatmentsActionPerformed(evt);
            }
        });
        getContentPane().add(searchtreatments, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 190, 70));

        seetasks.setBorderPainted(false);
        seetasks.setContentAreaFilled(false);
        seetasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seetasksActionPerformed(evt);
            }
        });
        getContentPane().add(seetasks, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 190, 70));

        toolmonitor.setBorderPainted(false);
        toolmonitor.setContentAreaFilled(false);
        toolmonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolmonitorActionPerformed(evt);
            }
        });
        getContentPane().add(toolmonitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 580, 200, 50));

        seeall.setText("See all");
        seeall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeallActionPerformed(evt);
            }
        });
        getContentPane().add(seeall, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 600, -1, -1));

        updateharvest.setBorderPainted(false);
        updateharvest.setContentAreaFilled(false);
        updateharvest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateharvestActionPerformed(evt);
            }
        });
        getContentPane().add(updateharvest, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 190, 60));

        jTable1.setBackground(new java.awt.Color(211, 216, 210));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "P_ID", "name", "w_amount", "nut_amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 910, 450));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seetask copy.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchtreatmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchtreatmentsActionPerformed
          SearchTreatment view = new SearchTreatment  ();
        view.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_searchtreatmentsActionPerformed

    private void seetasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seetasksActionPerformed
          SeeTask view = new SeeTask  ();
        view.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_seetasksActionPerformed

    private void updateharvestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateharvestActionPerformed
          EnterHarvest view = new EnterHarvest ();
        view.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_updateharvestActionPerformed

    private void toolmonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolmonitorActionPerformed
        // TODO add your handling code here:
        toolmonitor view = new toolmonitor ();
        view.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_toolmonitorActionPerformed

    private void seeallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeallActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seeallActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeeTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeeTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeeTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeeTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeeTask().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton searchtreatments;
    private javax.swing.JButton seeall;
    private javax.swing.JButton seetasks;
    private javax.swing.JButton toolmonitor;
    private javax.swing.JButton updateharvest;
    // End of variables declaration//GEN-END:variables
}
